export default class RecipesData {
  recipes = [
    {
      id: 1,
      name: "Barbecue Chicken",
      img: "barbeque-chicken.jpg",
      yields: 4,
      cookTime: 45,
      ingredients: [
        "cup of sugar",
        "1 tsp of vinegar",
        "2 tbsp of ketchup",
        "2 chicken breasts",
      ],
      instructions: [
        "mix the sauce ingredients in a large bowl",
        "add chicken and store in the fridge for at least 1 hour",
        "pour 1 tbsp of olive oil in a pan",
        "add chicken and stir-fry until golden brown",
      ],
      synopsis: "A great summer recipe!",
    },
    {
      id: 2,
      name: "Mashed Potatoes",
      img: "creamy-mashed-potatoes.jpg",
      yields: 4,
      cookTime: 30,
      ingredients: [
        "2 pounds potatoes",
        "1 teaspoon salt",
        "1/2 cup hot milk",
        "1/3 cup unsalted butter",
        "6 cloves fresh garlic",
        "1/4 cup sour cream",
        "salt and pepper, to taste",
        "1 tbsp fresh parsley",
      ],
      instructions: [
        "Peel and cut potatoes",
        "Place potatoes in a large pot and cover with cold, salted water",
        "Boil on medium for about 20minutes",
        "heat 1 tablespoon of the butter",
        "Sauté garlic until fragrant, about 1 minute",
        "Drain cooked potatoes",
        "add in the remaining butter, cooked garlic, " +
          "hot milk and sour cream",
        "Mash the potatoes with a potato masher until smooth",
        "Add in the parmesan cheese",
        "Season with salt and pepper to taste",
      ],
      synopsis: "Easy creamy mashed potatoes",
    },
    {
      id: 3,
      name: "Basic Smoothie",
      img: "smoothy.jpg",
      yields: 2,
      cookTime: 10,
      ingredients: [
        "2 cups frozen fruit (any kind)",
        "1 cup liquid (almond milk, orange juice, water, etc.)",
        "handful of greens (spinach, kale, etc.)",
        "1/2 cup nonfat Greek yogurt",
      ],
      instructions: [
        "Place all ingredients into a high-speed blender",
        "Blend on high until smooth",
        "Serve immediately and top with your favorite toppings",
      ],
      synopsis: "Healthy smoothie for breakfast",
    },
    {
      id: 4,
      name: "Deruny",
      img: "deruny.jpg",
      yields: 4,
      cookTime: 30,
      ingredients: [
        "Large yukon potatoes",
        "Small yellow onion",
        "Large egg",
        "All-purpose flour",
        "Fine salt",
        "Baking soda",
        "Grapeseed oil for frying",
        "Sour cream to serve",
      ],
      instructions: [
        "Grate potatoes and onion",
        "Stir in egg and dry ingredients (flour, salt and baking soda)",
        "Heat a lightly oiled skillet over medium heat",
        "Spoon pancake batter into skillet",
        "Fry each side for few minutes until golden brown",
        "Serve with sour cream",
      ],
      synopsis: "Ukrainian potato pancakes",
    },
    {
      id: 5,
      name: "Meatballs",
      img: "meatballs.jpg",
      yields: 12,
      cookTime: 30,
      ingredients: [
        "1 lb ground beef",
        "1 lb ground pork",
        "1/2 cup Italian breadcrumbs",
        "1/3 cup milk",
        "1/4 cup onion, diced",
        "1/2 teaspoon garlic powder",
        "1 teaspoon Italian seasoning",
        "1 egg",
        "1/4 cup parsley chopped",
        "1/4 cup shredded parmesan",
        "salt and pepper to taste",
      ],
      instructions: [
        "Preheat oven to 400 degrees F. ",
        "In a medium bowl, mix all ingredients until just combined.",
        "Shape mixture into 48 meatballs, " +
          "approximately 1 1/2 tablespoons each. ",
        "Bake 18-20 minutes or until cooked through. ",
      ],
      synopsis: "Excellent meatball recipe!",
    },
    {
      id: 6,
      name: "Chocolate Chip Cookies",
      img: "chocolate-chip-cookies.jpg",
      yields: 6,
      cookTime: 30,
      ingredients: [
        "1 cup butter",
        "1 package chocolate chips",
        "1 teaspoon baking soda",
        "1 teaspoon vanilla",
        "1/2 cup milk",
        "1/2 teaspoon salt",
        "2 egg",
        "3 1/2 cups flour",
        "3/4 cup brown sugar",
        "3/4 cup granulated sugar",
      ],
      instructions: [
        "Cream butter and sugars.",
        "Add eggs and vanilla.",
        "Sift dry ingredients; add with milk.",
        "Add chocolate chips.",
        "Bake at 375º for 10 minutes or until golden brown.",
      ],
      synopsis: "Delicious chocolate cookies!",
    },
    {
      id: 7,
      name: "Pesto Lasagna Rolls",
      img: "pesto-lasagna-rolls.jpg",
      yields: "6-8",
      cookTime: 80,
      ingredients: [
        "12 lasagna noodles",
        "2 tbsp. unsalted butter",
        "2 tbsp. flour",
        "1 1/2 cups whole milk",
        "1 large egg",
        "2 cups whole milk ricotta",
        "1 package chopped spinach",
        "2 1/2 cups shredded mozzarella",
        "3/4 cup grated Parmesan",
        "1 cup store-bought pesto",
        "1 tbsp. extra-virgin olive oil",
      ],
      instructions: [
        "preheat the oven to 425 degrees F.",
        "Bring a large pot of salted water to a boil.",
        "Cook the lasagna noodles 1 minute longer than the package directions",
        "Drain well and rinse with cold water.",
        "Meanwhile, melt the butter in a medium saucepan over medium heat.",
        "Add the flour and cook, stirring, until lightly toasted, about 2 minutes.",
        "Beat the egg in a large bowl and then stir in the ricotta, spinach, 1 1/2 cups of the mozzarella cheese, 1/2 cup of the Parmesan, 1/2 cup of the pesto, a large pinch of salt and a few grinds of pepper. ",
        "Stir the remaining 1/2 cup pesto into the slightly cooled bechamel sauce.",
        "Brush a 13- by 9- inch baking dish with oil.",
        "Spread 1/4 cup of the pesto-bechamel sauce on to the bottom of the dish.",
        "Lay half of the cooked lasagna noodles on a clean work surface and spread 1/3 cup of the ricotta mixture evenly over each.",
        "Starting with a short end, roll each noodle up.",
        "As you make the rolls, transfer them to the prepared baking dish seam-side down.",
        "Cover with foil and bake until the rolls are heated through and the sauce is bubbling, about 20 minutes.",
        "Remove the foil and bake until the cheese is browned on top, about 10 minutes.",
        "Sprinkle with crushed red pepper, if using, and let stand for 5 minutes before serving.",
      ],
      synopsis: "Traditional deep-dish lasagna!",
    },
    {
      id: 8,
      name: "Funeral Potatoes",
      img: "funeral-potatoes.jpg",
      yields: 12,
      cookTime: 75,
      ingredients: [
        "8 tablespoons (1 stick) salted butter",
        "One 28 bag frozen shredded hash brown potatoes",
        "1 medium onion, finely diced",
        "1/4 cup all-purpose flour ",
        "1 cup milk ",
        "2 cups low-sodium chicken broth ",
        "Kosher salt and freshly ground black pepper",
        "1 1/2 cups grated Monterey Jack cheese ",
        "1 cup sour cream ",
        "1/2 cup grated sharp Cheddar",
        "2 cups kettle-cooked potato chips ",
        "1/4 cup grated Parmesan",
      ],
      instructions: [
        "Preheat the oven to 350 degrees F. Grease a 9-by-13-inch baking dish with 1 tablespoon of the butter.",
        "Take the potatoes out of the freezer while you are preparing the rest of the ingredients.",
        "Heat a large, deep skillet over medium-high heat, then melt 6 tablespoons of the butter in it.",
        "Add the onions and cook, stirring occasionally, until the onions start to soften, 3 to 4 minutes. ",
        "Add the hash brown potatoes and mix everything together.",
        "Melt the remaining 1 tablespoon butter in a small pan.",
        "Put the potato chips and Parmesan in a bowl and crush the potato chips.",
        "Pour in the melted butter and toss to coat.",
        "Sprinkle the crumbs over the top of the potatoes.",
        "Cover with foil and bake for 20 minutes",
        "Remove the foil and continue baking until golden brown on top and bubbling around the edges, about 15 minutes more. ",
        "Let rest for 15 minutes before serving.",
      ],
      synopsis: "A super-delicious potato dish!",
    },
    {
      id: 9,
      name: "Roasted Brussels Sprouts",
      img: "roasted-brussel-sprouts.jpg",
      yields: 6,
      cookTime: 10,
      ingredients: [
        "1 1/2 pounds Brussels sprouts",
        "3 tablespoons good olive oil",
        "3/4 teaspoon kosher salt",
        "1/2 teaspoon freshly ground black pepper",
      ],
      instructions: [
        "Preheat oven to 400 degrees F.",
        "Cut off the brown ends of the Brussels sprouts and pull off any yellow outer leaves",
        "Mix them in a bowl with the olive oil, salt and pepper.",
        "Pour them on a sheet pan and roast for 35 to 40 minutes, until crisp on the outside and tender on the inside.",
        "Shake the pan from time to time to brown the sprouts evenly.",
        "Sprinkle with more kosher salt, and serve immediately.",
      ],
      synopsis: "Tender crispy sprouts!",
    },
    {
      id: 10,
      name: "Stuffed Bell Peppers",
      img: "stuffed-bell-peppers.jpg",
      yields: "4-6",
      cookTime: 95,
      ingredients: [
        "6 bell peppers, any color",
        "4 tablespoons olive oil",
        "8 ounces lean ground beef ",
        "salt and freshly ground black pepper",
        "1 onion, finely diced ",
        "2 cloves garlic, chopped",
        "1 medium zucchini, finely diced ",
        "4 tomatoes, seeded and finely diced ",
        "Red pepper flakes",
        "1 cup cooked long-grain and wild rice ",
        "1 1/2 cups grated pepper Jack cheese",
      ],
      instructions: [
        "Preheat the oven to 350 degrees F.",
        "Cut the tops off the peppers.",
        "Remove and discard the stems, then finely chop the tops; set aside.",
        "Scoop out the seeds and as much of the membrane as you can. ",
        "Place the peppers cut-side up in a baking dish just large enough to hold them upright.",
        "Heat 2 tablespoons of the olive oil in a large skillet over medium-high heat.",
        "Add the beef, season with salt and pepper",
        "Cook, breaking up the lumps, until the meat is cooked through and just beginning to brown, 8 to 10 minutes.",
        "Wipe out the skillet and add the remaining 2 tablespoons olive oil.",
        "Add the onions and chopped peppers and cook until beginning to soften, 3 to 4 minutes.",
        "Add the garlic and zucchini and cook for another minute.",
        "Add the tomatoes and season with salt and a pinch or 2 of red pepper flakes.",
        "Cook until everything is heated through, then stir in the beef and rice.",
        "Fill the peppers with the rice mixture and top each with a sprinkle of the remaining 1/2 cup cheese.",
        "Cover with foil and bake for 30 minutes.",
        "Uncover and bake until the peppers are soft and the cheese is melted and lightly browned, another 15 to 20 minutes.",
      ],
      synopsis: "A fun way to eat your vegetables!",
    },
  ];

  getAllRecipes = () => {
    return this.recipes;
  };

  getRecipe = (id) => {
    return this.recipes.filter((recipe) => recipe.id === id);
  };
}
